### ISSUE TITLE
是否漏传了“移动计算与应用开发”

### ISSUE THREAD

**Issue by AKmoex** [sunmiao0301/HFUT-CS#1]
学长，貌似漏传了“移动计算与应用开发“这门课程的学习资料了？

不知能否提供一下呢

**Comment by AKmoex** [comment]
找到了，原来是放在大二下了

**Comment by sunmiao0301** [comment]
好的


在 2021-07-31 09:34:22，"AKmoex" ***@***.***> 写道：

学长，貌似漏传了“移动计算与应用开发“这门课程的学习资料了？

不知能否提供一下呢
