### ISSUE TITLE
关于硬件综合设计

### ISSUE THREAD

**Issue by Astoria5zi** [sunmiao0301/HFUT-CS#4]
学长你好，请问多周期CPU设计，仿真结果和上板结果不一致是怎么回事呀

**Comment by Astoria5zi** [comment]
仿真结果正确，但是烧进板子第二条指令后似乎就出现偏差了，能拜托学长指点一下嘛

**Comment by sunmiao0301** [comment]
嗯嗯 我在度元旦假期 电脑不在身边 3号下午回去 你们哪天验收呢？



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年01月01日 21:40 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | Re: [sunmiao0301/HFUT-CS] 关于硬件综合设计 (Issue #4) |

仿真结果正确，但是烧进板子第二条指令后似乎就出现偏差了，能拜托学长指点一下嘛

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Astoria5zi** [comment]
学长我们下周一开始验收，19周前应该要验收完




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sunmiao0301/HFUT-CS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月1日(星期六) 晚上10:36
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [sunmiao0301/HFUT-CS] 关于硬件综合设计 (Issue #4)





 嗯嗯 我在度元旦假期 电脑不在身边 3号下午回去 你们哪天验收呢？
 
 
 
 ---- 回复的原邮件 ----
 | 发件人 | ***@***.***&gt; |
 | 日期 | 2022年01月01日 21:40 |
 | 收件人 | ***@***.***&gt; |
 | 抄送至 | ***@***.***&gt; |
 | 主题 | Re: [sunmiao0301/HFUT-CS] 关于硬件综合设计 (Issue #4) |
 
 仿真结果正确，但是烧进板子第二条指令后似乎就出现偏差了，能拜托学长指点一下嘛
 
 —
 Reply to this email directly, view it on GitHub, or unsubscribe.
 Triage notifications on the go with GitHub Mobile for iOS or Android.
 You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt; 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by sunmiao0301** [comment]
好的 我下周一回公寓帮你排错 元旦在外面放松😂



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年01月01日 22:45 |
| 收件人 | ***@***.***> |
| 抄送至 | Miao ***@***.******@***.***> |
| 主题 | Re: [sunmiao0301/HFUT-CS] 关于硬件综合设计 (Issue #4) |

学长我们下周一开始验收，19周前应该要验收完




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "sunmiao0301/HFUT-CS" ***@***.***&gt;;
发送时间:&nbsp;2022年1月1日(星期六) 晚上10:36
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [sunmiao0301/HFUT-CS] 关于硬件综合设计 (Issue #4)





嗯嗯 我在度元旦假期 电脑不在身边 3号下午回去 你们哪天验收呢？



---- 回复的原邮件 ----
| 发件人 | ***@***.***&gt; |
| 日期 | 2022年01月01日 21:40 |
| 收件人 | ***@***.***&gt; |
| 抄送至 | ***@***.***&gt; |
| 主题 | Re: [sunmiao0301/HFUT-CS] 关于硬件综合设计 (Issue #4) |

仿真结果正确，但是烧进板子第二条指令后似乎就出现偏差了，能拜托学长指点一下嘛

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Astoria5zi** [comment]
嗯嗯好的学长，太感谢了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sunmiao0301/HFUT-CS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月1日(星期六) 晚上11:06
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [sunmiao0301/HFUT-CS] 关于硬件综合设计 (Issue #4)





 好的 我下周一回公寓帮你排错 元旦在外面放松😂
 
 
 
 ---- 回复的原邮件 ----
 | 发件人 | ***@***.***&gt; |
 | 日期 | 2022年01月01日 22:45 |
 | 收件人 | ***@***.***&gt; |
 | 抄送至 | Miao ***@***.******@***.***&gt; |
 | 主题 | Re: [sunmiao0301/HFUT-CS] 关于硬件综合设计 (Issue #4) |
 
 学长我们下周一开始验收，19周前应该要验收完
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------
 发件人: "sunmiao0301/HFUT-CS" ***@***.***&amp;gt;;
 发送时间:&amp;nbsp;2022年1月1日(星期六) 晚上10:36
 ***@***.***&amp;gt;;
 ***@***.***&amp;gt;;"State ***@***.***&amp;gt;;
 主题:&amp;nbsp;Re: [sunmiao0301/HFUT-CS] 关于硬件综合设计 (Issue #4)
 
 
 
 
 
 嗯嗯 我在度元旦假期 电脑不在身边 3号下午回去 你们哪天验收呢？
 
 
 
 ---- 回复的原邮件 ----
 | 发件人 | ***@***.***&amp;gt; |
 | 日期 | 2022年01月01日 21:40 |
 | 收件人 | ***@***.***&amp;gt; |
 | 抄送至 | ***@***.***&amp;gt; |
 | 主题 | Re: [sunmiao0301/HFUT-CS] 关于硬件综合设计 (Issue #4) |
 
 仿真结果正确，但是烧进板子第二条指令后似乎就出现偏差了，能拜托学长指点一下嘛
 
 —
 Reply to this email directly, view it on GitHub, or unsubscribe.
 Triage notifications on the go with GitHub Mobile for iOS or Android.
 You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&amp;gt;
 —
 Reply to this email directly, view it on GitHub, or unsubscribe.
 Triage notifications on the go with GitHub Mobile for iOS or Android.
 You are receiving this because you modified the open/close state.Message ID: ***@***.***&amp;gt;
 
 —
 Reply to this email directly, view it on GitHub, or unsubscribe.
 Triage notifications on the go with GitHub Mobile for iOS or Android.
 You are receiving this because you commented.Message ID: ***@***.***&gt; 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Astoria5zi** [comment]
学长我的qq是2431221241,或者学长你留一下联系方式。等你度假完方便联系




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sunmiao0301/HFUT-CS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月1日(星期六) 晚上11:06
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [sunmiao0301/HFUT-CS] 关于硬件综合设计 (Issue #4)





 好的 我下周一回公寓帮你排错 元旦在外面放松😂
 
 
 
 ---- 回复的原邮件 ----
 | 发件人 | ***@***.***&gt; |
 | 日期 | 2022年01月01日 22:45 |
 | 收件人 | ***@***.***&gt; |
 | 抄送至 | Miao ***@***.******@***.***&gt; |
 | 主题 | Re: [sunmiao0301/HFUT-CS] 关于硬件综合设计 (Issue #4) |
 
 学长我们下周一开始验收，19周前应该要验收完
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------
 发件人: "sunmiao0301/HFUT-CS" ***@***.***&amp;gt;;
 发送时间:&amp;nbsp;2022年1月1日(星期六) 晚上10:36
 ***@***.***&amp;gt;;
 ***@***.***&amp;gt;;"State ***@***.***&amp;gt;;
 主题:&amp;nbsp;Re: [sunmiao0301/HFUT-CS] 关于硬件综合设计 (Issue #4)
 
 
 
 
 
 嗯嗯 我在度元旦假期 电脑不在身边 3号下午回去 你们哪天验收呢？
 
 
 
 ---- 回复的原邮件 ----
 | 发件人 | ***@***.***&amp;gt; |
 | 日期 | 2022年01月01日 21:40 |
 | 收件人 | ***@***.***&amp;gt; |
 | 抄送至 | ***@***.***&amp;gt; |
 | 主题 | Re: [sunmiao0301/HFUT-CS] 关于硬件综合设计 (Issue #4) |
 
 仿真结果正确，但是烧进板子第二条指令后似乎就出现偏差了，能拜托学长指点一下嘛
 
 —
 Reply to this email directly, view it on GitHub, or unsubscribe.
 Triage notifications on the go with GitHub Mobile for iOS or Android.
 You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&amp;gt;
 —
 Reply to this email directly, view it on GitHub, or unsubscribe.
 Triage notifications on the go with GitHub Mobile for iOS or Android.
 You are receiving this because you modified the open/close state.Message ID: ***@***.***&amp;gt;
 
 —
 Reply to this email directly, view it on GitHub, or unsubscribe.
 Triage notifications on the go with GitHub Mobile for iOS or Android.
 You are receiving this because you commented.Message ID: ***@***.***&gt; 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by sunmiao0301** [comment]
详细步骤已更新到
[见pdf docx](https://github.com/sunmiao0301/HFUT-CS/tree/main/%E5%A4%A7%E5%AD%A6%E4%B8%89%E5%B9%B4%E7%BA%A7%E4%B8%8B%E5%AD%A6%E6%9C%9F/%E7%B3%BB%E7%BB%9F%E8%BD%AF%E4%BB%B6%E7%BB%BC%E5%90%88%E8%AE%BE%E8%AE%A1-%E6%93%8D%E4%BD%9C%E7%B3%BB%E7%BB%9F%EF%BC%88%E7%8E%B0%E6%94%B9%E5%90%8D%E4%B8%BA%E6%93%8D%E4%BD%9C%E7%B3%BB%E7%BB%9F%E8%AF%BE%E7%A8%8B%E8%AE%BE%E8%AE%A1%EF%BC%89)
